apiVersion: v1
kind: Pod
metadata:
  name: log-gen
spec:
  containers:
  - name: log-gen
    image: bryanlatten/docker-log-gen
    ports:
    - containerPort: 3000
    livenessProbe:
      httpGet:
        path: /?n=1000&l=1024
        port: 3000
      initialDelaySeconds: 10
      periodSeconds: 5
